# 默认模式：端口 8761
server:
  port: 8761

# 服务信息
spring:
  application:
    name: @project.artifactId@

---
# 单机模式
# eureka.client.register-with-eureka: 是否将自己注册到 Eureka server,默认true
# eureka.client.fetch-registry: 此服务是否要去注册中心，获取服务列表信息,默认true
spring:
  profiles: singleton

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


######--------集群模式-------######
---
spring:
  profiles: cluster-1
  application:
    name: @project.artifactId@-1

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

---
spring:
  profiles: cluster-2
  application:
    name: @project.artifactId@-2

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

---
spring:
  profiles: cluster-3
  application:
    name: @project.artifactId@-3

server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/