spring:
  application:
    name: @project.artifactId@

server:
  port: 9090

# eureka 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://master.docker:8761/eureka/,http://master.docker:8762/eureka/,http://master.docker:8763/eureka/

