---
spring:
  application:
    name: "@pom.artifactId@"
  profiles:
    active: secure

# 非安全模式
---
spring:
  profiles: insecure

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

# 安全模式
---
spring:
  profiles: secure
  boot:
    admin:
      username: "${security.user.name}"
      password: "${security.user.password}"
  application:
    name: springboot-admin
security:
  user:
    name: admin
    password: 123456

# 日志配置
logging:
  level:
    org.springframework.security: DEBUG

zuul.sensitiveHeaders: