# info 信息,springboot 将占位符修改为@...@格式
info:
  app:
    groupId: cn.selinx
    artifactId: springcloud-eureka-server
    version: 0.0.1

# 默认模式：端口 8761
server:
  port: 8761

# 服务信息 # 忽略docker,veth,Virtual开头的网卡
spring:
  application:
    name: @project.artifactId@
  cloud:
    inetutils:
      ignored-interfaces: docker.*,veth.*,Virtual.*


# eureka 客户端配置，显示ip
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false

---
# 单机模式
# eureka.client.register-with-eureka: 是否将自己注册到 Eureka server,默认true
# eureka.client.fetch-registry: 此服务是否要去注册中心，获取服务列表信息,默认true
spring:
  profiles: singleton

info:
  app:
    name: singleton

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  server:
    enable-self-preservation: false


######--------集群模式-------######
---
info:
  app:
    name: cluster-1

spring:
  profiles: cluster-1

server:
  port: 8761

eureka:
  instance:
    hostname: master.docker
  client:
    service-url:
      defaultZone: http://master.docker:8761/eureka/,http://master.docker:8762/eureka/,http://master.docker:8763/eureka/

---
spring:
  profiles: cluster-2


server:
  port: 8762

eureka:
  instance:
    hostname: master.docker
  client:
    service-url:
      defaultZone: http://master.docker:8761/eureka/,http://master.docker:8762/eureka/,http://master.docker:8763/eureka/

---
spring:
  profiles: cluster-3


server:
  port: 8763

eureka:
  instance:
    hostname: master.docker
  client:
    service-url:
      defaultZone: http://master.docker:8761/eureka/,http://master.docker:8762/eureka/,http://master.docker:8763/eureka/